#!/bin/bash
keyvault=$1
certname=$2

certfile="$certname.crt"
keyfile="$certname.key"
pfxfile="$certname.pfx"

function downloadCerts {
	echo "Downloading cert"
	temp_certfile="$certname.$$.crt"
	temp_keyfile="$certname.$$.key"
        az keyvault certificate download --vault-name $keyvault --name $certname --f $temp_certfile
	az keyvault secret download --vault-name $keyvault --name $certname --f $temp_keyfile
	mv -f $temp_certfile $certfile
	mv -f $temp_keyfile $keyfile
	echo "Exporting pfx"
	openssl pkcs12 -export -out $pfxfile -inkey $keyfile -in $certfile
}

if test -f "$certfile"; then
        echo "Certificate exists, checking if it is close to expiration"
        enddate=$(openssl x509 -enddate -noout -in $certfile)
        datepart=${enddate#"notAfter="}
        endstamp=$(date --date="$datepart" +"%s")
        echo "Expires: $endstamp"
        now=$(date +"%s")
        echo "Now    : $now"

 	let renewby="$endstamp - (3600 * 24)"

	if [ $now -gt $renewby ]; then
		echo "Certificate needs to be downloaded"
		downloadCerts
	fi
else
        echo "Certificate has not been downloaded, attempting to do so now"
	downloadCerts
fi
